version: "3.8"

services:
  # MongoDB para OrderAnalyze e CreditAnalysis
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    networks:
      - barberShop-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"

  # PostgreSQL para ClientCardCredit
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: barberShop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - barberShop-network
    ports:
      - "5432:5432"

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - barberShop-network
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: redpandadata/console:latest
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - barberShop-network
    environment:
      KAFKA_BROKERS: "kafka:29092"
    depends_on:
      - kafka


networks:
  barberShop-network:
    driver: bridge