server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Cookie
          routes:
            - id: client-service
              uri: http://localhost:8081
              predicates:
                - Path=/clients/**

            - id: barbershop-service
              uri: http://localhost:8082
              predicates:
                - Path=/barbershops/**

            - id: professional-service
              uri: http://localhost:8083
              predicates:
                - Path=/professionals/**

            - id: schedule-service
              uri: http://localhost:8084
              predicates:
                - Path=/schedules/**

